workflows:
  attendEase-apk:
    name: AttendEase Optimized APK Build
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Build optimized APKs
        script: |
          cd flutter_project
          flutter clean
          flutter pub get
          flutter build apk --release
          flutter build apk --release --split-per-abi

    artifacts:
      - flutter_project/build/app/outputs/flutter-apk/*.apk
