import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'package:cross_file/cross_file.dart';

import '../models/models.dart';
import '../utils/app_theme.dart';

class PdfService {
  Future<void> generateClassReport({
    required SchoolClass schoolClass,
    required Teacher teacher,
    required List<Student> students,
    required List<AttendanceRecord> records,
    required DateTime from,
    required DateTime to,
    required String reportType,
  }) async {
    final pdf = pw.Document();
    final logo = await _loadLogo();
    final dateFmt = DateFormat('dd MMM yyyy');

    final byStudent = <int, List<AttendanceRecord>>{};
    for (final r in records) {
      byStudent.putIfAbsent(r.studentId, () => []).add(r);
    }

    int countStatus(List<AttendanceRecord> rs, String status) =>
        rs.where((r) => r.status == status).length;

    final totalPresent = countStatus(records, 'present');
    final totalAbsent = countStatus(records, 'absent');
    final totalLate = countStatus(records, 'late');

    String title = switch (reportType) {
      'daily' => 'Daily Attendance Register',
      'weekly' => 'Weekly Attendance Summary',
      'monthly' => 'Monthly Attendance Summary',
      'term1' => 'Term 1 Attendance Summary',
      'term2' => 'Term 2 Attendance Summary',
      'term3' => 'Term 3 Attendance Summary',
      _ => 'Attendance Summary'
    };

    String termLabel = switch (reportType) {
      'term1' => 'Term 1',
      'term2' => 'Term 2',
      'term3' => 'Term 3',
      _ => 'Custom Range'
    };

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        build: (context) => [
          _header(
            logo: logo,
            title: title,
            schoolClass: schoolClass,
            teacher: teacher,
            from: from,
            to: to,
            termLabel: reportType.startsWith('term') ? termLabel : null,
          ),
          pw.SizedBox(height: 16),
          pw.Row(
            children: [
              _statBox('Students', '${students.length}', PdfColors.blue50),
              pw.SizedBox(width: 8),
              _statBox('Present', '$totalPresent', PdfColors.green50),
              pw.SizedBox(width: 8),
              _statBox('Absent', '$totalAbsent', PdfColors.red50),
              pw.SizedBox(width: 8),
              _statBox('Late', '$totalLate', PdfColors.amber50),
            ],
          ),
          pw.SizedBox(height: 16),
          pw.TableHelper.fromTextArray(
            border: pw.TableBorder.all(color: PdfColors.grey300, width: .5),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.blue50),
            cellPadding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 8),
            columnWidths: {
              0: const pw.FixedColumnWidth(24),
              1: const pw.FixedColumnWidth(75),
              2: const pw.FlexColumnWidth(3),
              3: const pw.FixedColumnWidth(55),
              4: const pw.FixedColumnWidth(50),
              5: const pw.FixedColumnWidth(40),
            },
            headers: const ['#', 'Adm No.', 'Student Name', 'Present', 'Absent', 'Late'],
            data: [
              for (int i = 0; i < students.length; i++)
                [
                  '${i + 1}',
                  students[i].admissionNo,
                  students[i].name,
                  '${countStatus(byStudent[students[i].id] ?? const [], 'present')}',
                  '${countStatus(byStudent[students[i].id] ?? const [], 'absent')}',
                  '${countStatus(byStudent[students[i].id] ?? const [], 'late')}',
                ]
            ],
          ),
          pw.SizedBox(height: 24),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              _signature('Teacher Signature'),
              _signature('Admin Signature'),
            ],
          ),
          pw.SizedBox(height: 10),
          pw.Text(
            'Generated by ${AppTheme.appName} • ${dateFmt.format(DateTime.now())}',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
        ],
      ),
    );

    final bytes = await pdf.save();
    final dir = await getTemporaryDirectory();
    final filename = 'attendease_${schoolClass.name.replaceAll(' ', '_').toLowerCase()}_${DateFormat('yyyyMMdd_HHmm').format(DateTime.now())}.pdf';
    final file = File('${dir.path}/$filename');
    await file.writeAsBytes(bytes, flush: true);

    await Share.shareXFiles(
      [XFile(file.path)],
      text: '${AppTheme.appName} report for ${schoolClass.name}',
    );
  }

  pw.Widget _header({
    required pw.MemoryImage? logo,
    required String title,
    required SchoolClass schoolClass,
    required Teacher teacher,
    required DateTime from,
    required DateTime to,
    String? termLabel,
  }) {
    final range = from.year == to.year && from.month == to.month && from.day == to.day
        ? DateFormat('dd MMM yyyy').format(from)
        : '${DateFormat('dd MMM yyyy').format(from)} - ${DateFormat('dd MMM yyyy').format(to)}';

    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        borderRadius: pw.BorderRadius.circular(12),
        border: pw.Border.all(color: PdfColors.blue100),
        color: PdfColors.blue50,
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            width: 60,
            height: 60,
            decoration: pw.BoxDecoration(
              color: PdfColors.white,
              borderRadius: pw.BorderRadius.circular(10),
            ),
            child: logo == null
                ? pw.Center(child: pw.Text('AIS', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)))
                : pw.Padding(
                    padding: const pw.EdgeInsets.all(6),
                    child: pw.Image(logo, fit: pw.BoxFit.contain),
                  ),
          ),
          pw.SizedBox(width: 14),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(AppTheme.schoolName,
                    style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 4),
                pw.Text(title, style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey800)),
                pw.SizedBox(height: 10),
                pw.Text('Class: ${schoolClass.name}', style: const pw.TextStyle(fontSize: 11)),
                pw.Text('Teacher: ${teacher.name}', style: const pw.TextStyle(fontSize: 11)),
                if (termLabel != null) pw.Text('Term: $termLabel', style: const pw.TextStyle(fontSize: 11)),
                pw.Text('Date: $range', style: const pw.TextStyle(fontSize: 11)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _statBox(String label, String value, PdfColor bg) => pw.Expanded(
        child: pw.Container(
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(color: bg, borderRadius: pw.BorderRadius.circular(10)),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(value, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 2),
              pw.Text(label, style: const pw.TextStyle(fontSize: 10)),
            ],
          ),
        ),
      );

  pw.Widget _signature(String label) => pw.Column(
        children: [
          pw.Container(width: 170, height: 1, color: PdfColors.grey700),
          pw.SizedBox(height: 6),
          pw.Text(label, style: const pw.TextStyle(fontSize: 11)),
        ],
      );

  Future<pw.MemoryImage?> _loadLogo() async {
    final candidates = [
      'assets/branding/school_logo.jpg',
      'assets/branding/school_logo.png',
    ];
    for (final path in candidates) {
      try {
        final data = await rootBundle.load(path);
        return pw.MemoryImage(Uint8List.fromList(data.buffer.asUint8List()));
      } catch (_) {
        // try next
      }
    }
    return null;
  }
}
